ch_cookie_consent:
    use_logger: true       # logs user actions to database
    simplified: true       # when set to true the user can only deny or accept all cookies at once
    http_only: true        # sets HttpOnly on cookies
    csrf_protection: true  # the cookie consent form is csrf protected or not
    position: 'bottom'     # top | bottom
    theme: 'dark'          # light | dark option
    categories:
        - 'analytics'
