framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    session:
        handler_id: null
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        storage_factory_id: 'session.storage.factory.native'
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: 'session.storage.factory.mock_file'

when@prod:
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: 'cache.app'
                doctrine.system_cache_pool:
                    adapter: 'cache.system'
