leapt_froala_editor:
    language: 'es'
    includeCodeMirror: false
    includeFontAwesome: false
    pluginsDisabled: [ 'save', 'fullscreen', 'print', 'spellcheck', 'video', 'image', 'imageManager', 'file', 'table' ]
    profiles:
        full:
            heightMax: 500
        compact:
            heightMax: 200
