leapt_froala_editor:
    includeCodeMirror: false
    includeFontAwesome: false
    attribution: false
    language: 'es'
    pluginsEnabled: [ 'align', 'link', 'lists', 'quote' ]
    pluginsDisabled: [ 'charCounter', 'codeBeautifier', 'codeView', 'colors', 'draggable', 'embedly', 'emoticons', 'entities', 'filesManager', 'file', 'fontAwesome', 'fontFamily', 'fontSize', 'fullscreen', 'help', 'image', 'imageManager', 'imageTui', 'inlineClass', 'inlineStyle', 'lineBreaker', 'lineHeight', 'markdownSupport', 'paragraphFormat', 'paragraphStyle', 'print', 'quickInsert', 'save', 'specialCharacters', 'spellChecker', 'trackChanges', 'table', 'url', 'video', 'wordCounter', 'wordPaste' ]
    profiles:
        full:
            heightMax: 450
        compact:
            heightMax: 200
