security:
    role_hierarchy:
        ROLE_SONATA_ADMIN:
            - 'ROLE_USER'
            - 'ROLE_ADMIN_MENU_LEVEL1_ALL'
            - 'ROLE_ADMIN_MENU_LEVEL2_ALL'
            - 'ROLE_ADMIN_SLIDESHOW_PAGE_ALL'
            - 'ROLE_ADMIN_PAGE_ALL'
            - 'ROLE_ADMIN_PAGE_IMAGE_ALL'
            - 'ROLE_ADMIN_NEWSLETTER_ALL'
            - 'ROLE_ADMIN_NEWSLETTER_GROUP_ALL'
            - 'ROLE_ADMIN_NEWSLETTER_POST_ALL'
            - 'ROLE_ADMIN_NEWSLETTER_USER_ALL'
            - 'ROLE_ADMIN_ARTIST_ALL'
            - 'ROLE_ADMIN_ARCHIVE_ALL'
            - 'ROLE_ADMIN_VISITING_HOURS_ALL'
            - 'ROLE_ADMIN_CONFIG_FOOTER_INFORMATION_ALL'
            - 'ROLE_ADMIN_CONFIG_CALENDAR_WORKING_DAY_ALL'
        ROLE_SONATA_SUPER_ADMIN:
            - 'ROLE_SONATA_ADMIN'
            - 'ROLE_ADMIN_USER_ALL'
        ROLE_ADMIN:
            - 'ROLE_SONATA_ADMIN'
        ROLE_SUPER_ADMIN:
            - 'ROLE_ADMIN'
            - 'ROLE_SONATA_SUPER_ADMIN'
            - 'ROLE_ALLOWED_TO_SWITCH'
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'email'
    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false
        admin:
            lazy: true
            pattern: '/admin(.*)'
            context: 'admin'
            provider: 'app_user_provider'
            form_login:
                login_path: 'admin_app_login'
                check_path: 'admin_app_login'
                failure_path: 'admin_app_login'
                username_parameter: 'email'
                password_parameter: 'password'
                enable_csrf: true
            logout:
                path: 'admin_app_logout'
                target: 'admin_app_login'
        main:
            lazy: true
    access_control:
        - { path: ^/admin/login$, roles: 'PUBLIC_ACCESS' }
        - { path: ^/admin/logout$, roles: 'PUBLIC_ACCESS' }
        - { path: ^/admin/, roles: 'ROLE_ADMIN' }
        - { path: ^/.*, roles: 'PUBLIC_ACCESS' }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: 'auto'
                cost: 4
                time_cost: 3
                memory_cost: 10
