controllers:
    type: 'attribute'
    resource:
        path: '../../src/Controller/Frontend/'
        namespace: 'App\Controller\Frontend'
    prefix:
        ca: ''
        es: 'es'

admins:
    type: 'attribute'
    resource:
        path: '../../src/Controller/Backend/'
        namespace: 'App\Controller\Backend'
