- name: refresh cache
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} cache:clear --no-warmup {{ symfony_cache_options }}"
- name: warm-up cache again
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} cache:warmup {{ symfony_cache_options }}"
- name: assets install
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} assets:install {{ symfony_cache_options }}"
- name: install ckeditor
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} ckeditor:install --tag=4.22.1 {{ symfony_cache_options }}"
- name: importmap install
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} importmap:install {{ symfony_cache_options }}"
- name: sass build
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} sass:build {{ symfony_cache_options }}"
- name: asset mapper compile
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} asset-map:compile {{ symfony_cache_options }}"
